GGMusicStore/Controllers/ControlPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.MusicInfo;
using AutoMapper;
using System.IO;
using Core.Shopping;

namespace GGMusicStore
{
    [Authorize(Roles = "Admin")]
    public class ControlPanelController : Controller
    {
        private AlbumService albumService;
        private GenreService genreService;
        private ArtistService artistService;
        private OrderService orderService;
        public ControlPanelController(AlbumService albumService, GenreService genreService, ArtistService artistService, OrderService orderService)
        {
            this.albumService = albumService;
            this.genreService = genreService;
            this.artistService = artistService;
            this.orderService = orderService;
        }

        /// <summary>
        /// 后台主页
        /// </summary>
        /// <returns></returns>
        public ActionResult Home()
        {
            return View();
        }

        #region 音乐流派管理

        /// <summary>
        /// 音乐流派管理
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageGenres()
        {

            return View();
        }
        /// <summary>
        /// 音乐流派列表
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _ListGenres()
        {
            var genres = genreService.GetAll();
            return PartialView(genres);
        }

        /// <summary>
        /// 编辑/添加音乐流派 GET
        /// </summary>
        /// <param name="genreId">音乐流派</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult _EditGenre(int genreId = 0)
        {
            Genre genre = new Genre();
            if (genreId > 0)
            {
                //编辑
                var genreCanBeNull = genreService.Get(genreId);
                if (genreCanBeNull != null)
                {
                    genre = genreCanBeNull;
                }
            }
            else
            {
                //添加
                genre = new Genre();
            }
            return View(genre);
        }

        /// <summary>
        /// 编辑/添加音乐流派 POST
        /// </summary>
        /// <param name="genreEditModel"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult _EditGenre(Genre genreEditModel)
        {
            if (ModelState.IsValid)
            {
                var genre = genreService.Get(genreEditModel.GenreId) ?? new Genre();
                genre.GenreName = genreEditModel.GenreName;
                genre.Description = genreEditModel.Description;
                if (genreEditModel.GenreId > 0)
                {
                    //编辑
                    genreService.Update(genre);
                    return Json(new { MessageType = 1, MessageContent = "成功编辑音乐流派" });
                }
                else
                {
                    //添加
                    genreService.Create(genre);
                    return Json(new { MessageType = 1, MessageContent = "成功添加音乐流派" });
                }
            }
            return Json(new { MessageType = 0, MessageContent = "添加音乐流派失败" });
        }

        /// <summary>
        /// 删除音乐流派
        /// </summary>
        /// <param name="genreId"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteGenre(int genreId)
        {
            if (genreId > 0)
            {
                genreService.Delete(genreId);
                return Json(new { MessageType = 1, MessageContent = "成功删除音乐流派" });
            }
            else
            {
                return Json(new { MessageType = 0, MessageContent = "删除音乐流派失败" });
            }

        }
        #endregion


        #region 音乐人管理
        /// <summary>
        /// 音乐人管理
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageArtists()
        {

            return View();
        }
        /// <summary>
        /// 音乐人列表
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _ListArtists()
        {
            var artists = artistService.GetAll();

            return PartialView(artists);
        }

        /// <summary>
        /// 编辑/添加音乐人 GET
        /// </summary>
        /// <param name="artistId">音乐人</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult _EditArtist(int artistId = 0)
        {
            ArtistEditModel artistEditModel = new ArtistEditModel();
            if (artistId > 0)
            {
                //编辑
                var artist = artistService.Get(artistId);
                if (artist != null)
                {
                    artistEditModel.ArtistId = artist.ArtistId;
                    artistEditModel.ArtistName = artist.ArtistName;
                    artistEditModel.Description = artist.Description;
                    if (!string.IsNullOrEmpty(artist.ArtistGenreIds))
                    {
                        artistEditModel.ArtistGenres = artist.ArtistGenreIds.Split(';');
                    }
                }
            }
            else
            {
                //添加
                //artistEditModel = new Artist();
            }
            var genresMultiSelect = new MultiSelectList(genreService.GetAll(), "GenreId", "GenreName", artistEditModel.ArtistGenres);
            ViewData["genresMultiSelect"] = genresMultiSelect;
            return View(artistEditModel);
        }

        /// <summary>
        /// 编辑/添加音乐人 POST
        /// </summary>
        /// <param name="artistEditModel"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult _EditArtist(ArtistEditModel artistEditModel)
        {
            if (ModelState.IsValid)
            {
                var artist = artistService.Get(artistEditModel.ArtistId) ?? new Artist();
                artist.ArtistName = artistEditModel.ArtistName;
                artist.Description = artistEditModel.Description;
                var artistGenresString = string.Join(";", artistEditModel.ArtistGenres ?? new List<string>());

                artist.ArtistGenreIds = artistGenresString;
                if (artistEditModel.ArtistId > 0)
                {
                    //编辑
                    artistService.Update(artist);
                    return Json(new { MessageType = 1, MessageContent = "成功编辑音乐人信息" });
                }
                else
                {
                    //添加
                    artistService.Create(artist);
                    return Json(new { MessageType = 1, MessageContent = "成功添加音乐人" });
                }
            }
            return Json(new { MessageType = 0, MessageContent = "添加音乐人失败" });
        }

        /// <summary>
        /// 删除音乐人
        /// </summary>
        /// <param name="artistId"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteArtist(int artistId)
        {
            if (artistId > 0)
            {
                artistService.Delete(artistId);
                return Json(new { MessageType = 1, MessageContent = "成功删除音乐人" });
            }
            else
            {
                return Json(new { MessageType = 0, MessageContent = "删除音乐人失败" });
            }

        }

        #endregion

        #region 音乐专辑管理
        /// <summary>
        /// 音乐专辑管理
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageAlbums()
        {
            return View();
        }
        /// <summary>
        /// 音乐专辑列表
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _ListAlbums(int pageSize = 20, int pageIndex = 1)
        {
            var albums = albumService.GetPagingData(pageSize, pageIndex);

            return PartialView(albums);
        }

        /// <summary>
        /// 编辑/添加音乐专辑 GET
        /// </summary>
        /// <param name="albumId">音乐专辑</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult _EditAlbum(int albumId = 0)
        {
            Album albumEditModel = new Album();
            if (albumId > 0)
            {
                //编辑
                albumEditModel = albumService.Get(albumId);
            }
            else
            {
                //添加
                //albumEditModel = new Album();
                albumEditModel.AlbumStatus = true;
            }

            ViewData["genresSelectList"] = new SelectList(genreService.GetAll(), "GenreId", "GenreName", albumEditModel.GenreId);
            ViewData["artistsSelectList"] = new SelectList(artistService.GetAll(), "ArtistId", "ArtistName", albumEditModel.ArtistId);

            return View(albumEditModel);
        }

        /// <summary>
        /// 编辑/添加音乐专辑 POST
        /// </summary>
        /// <param name="albumEditModel"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult _EditAlbum(Album albumEditModel)
        {
            if (ModelState.IsValid)
            {

                if (albumEditModel.AlbumId > 0)
                {
                    //编辑
                    var album = albumService.Get(albumEditModel.AlbumId);
                    album.GenreId = albumEditModel.GenreId;
                    album.ArtistId = albumEditModel.ArtistId;
                    album.AlbumName = albumEditModel.AlbumName;
                    album.Description = albumEditModel.Description;
                    album.AlbumNum = albumEditModel.AlbumNum;
                    album.Price = albumEditModel.Price;
                    album.Discount = albumEditModel.Discount;
                    //if (album.DiscountPrice > 0)
                    //{
                    //    album.DiscountPrice = albumEditModel.DiscountPrice;
                    //}
                    //else
                    //{

GGMusicStore/Controllers/ShoppingController.cs
using Core.MusicInfo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Shopping;

namespace GGMusicStore
{
    public class ShoppingController : Controller
    {
        private AlbumService albumService;
        private GenreService genreService;
        private ArtistService artistService;
        private CartService cartService;
        private OrderService orderService;

        public ShoppingController(AlbumService albumService, GenreService genreService, ArtistService artistService, CartService cartService, OrderService orderService)
        {
            this.albumService = albumService;
            this.genreService = genreService;
            this.artistService = artistService;
            this.cartService = cartService;
            this.orderService = orderService;

        }

        /// <summary>
        /// 导航栏购物车状态
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _CartLayout()
        {
            ViewData["CartCount"] = cartService.CountCartItems(cartService.GetCartId(this.HttpContext));
            return PartialView();
        }

        /// <summary>
        /// 购物车管理
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageCart()
        {
            return View();
        }

        /// <summary>
        /// 购物车列表
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _ListCartItems()
        {
            var cartId = cartService.GetCartId(this.HttpContext);
            var myCart = cartService.GetAllItemsInCart(cartId).ToList();
            ViewData["TotalMoney"] = cartService.GetTotalMoney(cartId);
            return PartialView(myCart);
        }

        /// <summary>
        /// 添加到购物车
        /// </summary>
        /// <param name="toCartNum"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddToCart(int albumId, int toCartNum)
        {

            if (albumId > 0 && toCartNum > 0)
            {
                var cartId = cartService.GetCartId(this.HttpContext);
                cartService.AddToCart(cartId, albumId, toCartNum);
                return Json(new { MessageType = 1, MessageContent = "添加成功" });

            }

            return Json(new { MessageType = 0, MessageContent = "添加失败" });
        }

        /// <summary>
        /// 从购物车中移除
        /// </summary>
        /// <param name="toCartNum"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteCartItem(int albumId, int deleteNum)
        {

            if (albumId > 0 && deleteNum > 0)
            {
                var cartId = cartService.GetCartId(this.HttpContext);
                cartService.DeleteCartItem(cartId, albumId, deleteNum);
                return Json(new { MessageType = 1, MessageContent = "删除成功" });

            }
            return Json(new { MessageType = 0, MessageContent = "添加失败" });
        }

        /// <summary>
        /// 清空购物车
        /// </summary>
        /// <param name="toCartNum"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult EmptyCart()
        {
            var cartId = cartService.GetCartId(this.HttpContext);
            cartService.EmptyCart(cartId);
            return Json(new { MessageType = 1, MessageContent = "成功清空购物车" });
        }

        /// <summary>
        /// 将购物车转移到某个用户下
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult MigrateCart()
        {
            if (!string.IsNullOrEmpty(this.HttpContext.Session["CartId"].ToString()))
            {
                cartService.MigrateCart(this.HttpContext.User.Identity.Name, cartService.GetCartId(this.HttpContext));
                HttpContext.Session["CartId"] = this.HttpContext.User.Identity.Name;
                return Json(new { MessageType = 1, MessageContent = "成功载入购物车" });
            }
            else
            {
                return Json(new { MessageType = 2, MessageContent = "赶快去挑选喜爱的专辑吧" });
            }
        }

        /// <summary>
        /// 判断专辑是否售罄
        /// </summary>
        /// <returns></returns>
        public JsonResult IsAllAlbumAvailable()
        {
            var IsAllAlbumAvailable = cartService.IsAllAlbumAvailable(cartService.GetCartId(this.HttpContext));
            if (IsAllAlbumAvailable)
            {
                return Json(new { MessageType = 1, MessageContent = "所有的专辑均在售卖中" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { MessageType = 0, MessageContent = "某些专辑已售罄" }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 编辑订单 GET
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public ActionResult _EditOrder()
        {
            var order = new Order();
            order.UserName = this.HttpContext.User.Identity.Name;
            order.Total = cartService.GetTotalMoney(cartService.GetCartId(this.HttpContext));
            return View(order);
        }

        /// <summary>
        /// 编辑订单 POST
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public JsonResult _EditOrder(FormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                Order order = new Order();
                TryUpdateModel<Order>(order, formCollection);
                var ispayed = formCollection.Get("isPayed");
                if (ispayed == "IsPayed")
                {
                    order.OrderDate = DateTime.Now;
                    //order.Total=
                    orderService.Create(order);
                    orderService.CreateOrder(order.OrderId, cartService.GetCartId(this.HttpContext));
                    return Json(new { MessageType = 1, MessageContent = "成功生成订单!" });
                }
                return Json(new { MessageType = 0, MessageContent = "请首先支付订单!" });
            }

            return Json(new { MessageType = 0, MessageContent = "订单创建失败" });
        }

    }
}

GGMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GGMusic</title>

    <meta charset="utf-8">
    <title>Worthy | Free Powerful Theme by HtmlCoder</title>
    <meta name="description" content="Worthy a Bootstrap-based, Responsive HTML5 Template">
    <meta name="author" content="htmlcoder.me">
    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/favicon.ico">

    <!-- Web Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700,300&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:700,400,300' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <!-- 模板中的js和css -->
    @Styles.Render("~/Content/Styles/template")
    @Styles.Render("~/Content/Styles/font-awesome")
    @Scripts.Render("~/bundles/Scripts/template")

    <!-- 插件 js -->
    @Scripts.Render("~/bundles/Scripts/isotope")
    @Scripts.Render("~/bundles/Scripts/backstretch")
    @Scripts.Render("~/bundles/Scripts/appear")
    @Styles.Render("~/Content/Styles/layer")
    @Scripts.Render("~/bundles/Scripts/layer")

</head>
<body class="no-trans">
    <!-- scrollToTop -->
    <!-- ================ -->
    <div class="scrollToTop"><i class="icon-up-open-big"></i></div>

    <!-- header start -->
    <!-- ================ -->
    <header class="header fixed clearfix navbar navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-md-4">

                    <!-- header-left start -->
                    <!-- ================ -->
                    <div class="header-left clearfix">

                        <!-- logo -->
                        <div class="logo smooth-scroll">
                            <a href="@Url.Action("Home","Home")"><img id="logo" src="~/images/GGMusicLogo.png" alt="GGMusicStore"></a>
                        </div>

                        <!-- name-and-slogan -->
                        <div class="site-name-and-slogan smooth-scroll">
                            <div class="site-name">
                                <a href="@Url.Action("Home","Home")"><img id="logo" src="~/images/GGMusic.png" alt="GGMusicStore"></a>
                                @*<a href="#banner" style="font-family:汉仪粗篆繁">GGMusic</a>*@
                            </div>
                            <div class="site-slogan">Music Anywhere By <a target="_blank" href="#">Smile_Gum_Gum</a></div>
                        </div>
                    </div>
                    <!-- header-left end -->
                </div>
                <div class="col-md-8">

                    <!-- header-right start -->
                    <!-- ================ -->
                    <div class="header-right clearfix">

                        <!-- main-navigation start -->
                        <!-- ================ -->
                        <div class="main-navigation animated">

                            <!-- navbar start -->
                            <!-- ================ -->
                            <nav class="navbar navbar-default" role="navigation">
                                <div class="container-fluid">

                                    <!-- Toggle get grouped for better mobile display -->
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                    </div>

                                    <!-- Collect the nav links, forms, and other content for toggling -->
                                    <div class="collapse navbar-collapse scrollspy smooth-scroll" id="navbar-collapse-1">
                                        @Html.Partial("_LoginPartial")
                                        <ul class="nav navbar-nav navbar-right">
                                            @*<li class="active"><a href="#banner">Home</a></li>
                                                <li><a href="#about">About</a></li>
                                                <li><a href="#services">Services</a></li>
                                                <li><a href="#portfolio">Portfolio</a></li>
                                                <li><a href="#clients">Clients</a></li>
                                                <li><a href="#contact">Contact</a></li>*@
                                            <li>@Html.ActionLink("Home", "Home", "Home")</li>
                                            <li>@Html.ActionLink("Store", "Store", "Store")</li>
                                            <li><a id="search" role="button" class="fa fa-search" href="javaScript:;"></a></li>
                                            <li id="_CartLayout">@Html.Action("_CartLayout", "Shopping")</li>

                                        </ul>

                                    </div>

                                </div>
                            </nav>
                            <!-- navbar end -->

                        </div>
                        <!-- main-navigation end -->

                    </div>
                    <!-- header-right end -->

                </div>
            </div>
        </div>
    </header>
    <!-- header end -->

    @RenderBody()

    <!-- .subfooter start -->
    <!-- ================ -->
    <div class="subfooter">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center">@DateTime.Now.Year - GGMusicStore @Html.ActionLink("管理", "Home", "ControlPanel")</p>
                </div>
            </div>
        </div>
    </div>
    <!-- .subfooter end -->
    @RenderSection("Scripts", false)


    <script>
        $('#search').on('click', function () {
            layer.open({
                type: 1,
                shade: [0.6,'#000000'],
                title: false,
                content: $('#searchPanel'),
                closeBtn: false,
                shadeClose:true
            });
            $('.input-search').focus();
        })

    </script>
    <div id="searchPanel" style="display:none">
        <div class="input-group" style="width:600px">
            <input type="text" class="form-control input-search" placeholder="可搜索流派、音乐人和专辑名称" style="height:38px">
            <span class="input-group-btn">
                <button class="btn btn-primary btn-search" type="button">搜索</button>
            </span>
        </div>
        <script>
        $('.btn-search').on('click', function () {
            var keyword = $('.input-search').val();
            window.location.href = '@Url.Action("Store","Store")?keyword=' + keyword+"#storeMain";
            @*$.get('@Url.Action("_ListAlbums","Store")', { keyword: keyword, t: (new Date()).valueOf() }, function (html) {
                $('#_ListAlbums').html(html);
                location.href = '#storeMain';
            });*@
        })

        $('.input-search').on('keyup', function (event) {
            if (event.keyCode == 13) {
                $('.btn-search').click();
            }
        })
        </script>
    </div>
</body>
</html>