GGMusicStore/Controllers/ShoppingController.cs
using Core.MusicInfo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Shopping;

namespace GGMusicStore
{
    public class ShoppingController : Controller
    {
        private AlbumService albumService;
        private GenreService genreService;
        private ArtistService artistService;
        private CartService cartService;
        private OrderService orderService;

        public ShoppingController(AlbumService albumService, GenreService genreService, ArtistService artistService, CartService cartService, OrderService orderService)
        {
            this.albumService = albumService;
            this.genreService = genreService;
            this.artistService = artistService;
            this.cartService = cartService;
            this.orderService = orderService;

        }

        /// <summary>
        /// 导航栏购物车状态
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _CartLayout()
        {
            ViewData["CartCount"] = cartService.CountCartItems(cartService.GetCartId(this.HttpContext));
            return PartialView();
        }

        /// <summary>
        /// 购物车管理
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageCart()
        {
            return View();
        }

        /// <summary>
        /// 购物车列表
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _ListCartItems()
        {
            var cartId = cartService.GetCartId(this.HttpContext);
            var myCart = cartService.GetAllItemsInCart(cartId).ToList();
            ViewData["TotalMoney"] = cartService.GetTotalMoney(cartId);
            return PartialView(myCart);
        }

        /// <summary>
        /// 添加到购物车
        /// </summary>
        /// <param name="toCartNum"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddToCart(int albumId, int toCartNum)
        {

            if (albumId > 0 && toCartNum > 0)
            {
                var cartId = cartService.GetCartId(this.HttpContext);
                cartService.AddToCart(cartId, albumId, toCartNum);
                return Json(new { MessageType = 1, MessageContent = "添加成功" });

            }

            return Json(new { MessageType = 0, MessageContent = "添加失败" });
        }

        /// <summary>
        /// 从购物车中移除
        /// </summary>
        /// <param name="toCartNum"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteCartItem(int albumId, int deleteNum)
        {

            if (albumId > 0 && deleteNum > 0)
            {
                var cartId = cartService.GetCartId(this.HttpContext);
                cartService.DeleteCartItem(cartId, albumId, deleteNum);
                return Json(new { MessageType = 1, MessageContent = "删除成功" });

            }
            return Json(new { MessageType = 0, MessageContent = "添加失败" });
        }

        /// <summary>
        /// 清空购物车
        /// </summary>
        /// <param name="toCartNum"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult EmptyCart()
        {
            var cartId = cartService.GetCartId(this.HttpContext);
            cartService.EmptyCart(cartId);
            return Json(new { MessageType = 1, MessageContent = "成功清空购物车" });
        }

        /// <summary>
        /// 将购物车转移到某个用户下
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult MigrateCart()
        {
            if (!string.IsNullOrEmpty(this.HttpContext.Session["CartId"].ToString()))
            {
                cartService.MigrateCart(this.HttpContext.User.Identity.Name, cartService.GetCartId(this.HttpContext));
                HttpContext.Session["CartId"] = this.HttpContext.User.Identity.Name;
                return Json(new { MessageType = 1, MessageContent = "成功载入购物车" });
            }
            else
            {
                return Json(new { MessageType = 2, MessageContent = "赶快去挑选喜爱的专辑吧" });
            }
        }

        /// <summary>
        /// 判断专辑是否售罄
        /// </summary>
        /// <returns></returns>
        public JsonResult IsAllAlbumAvailable()
        {
            var IsAllAlbumAvailable = cartService.IsAllAlbumAvailable(cartService.GetCartId(this.HttpContext));
            if (IsAllAlbumAvailable)
            {
                return Json(new { MessageType = 1, MessageContent = "所有的专辑均在售卖中" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { MessageType = 0, MessageContent = "某些专辑已售罄" }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 编辑订单 GET
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize]
        public ActionResult _EditOrder()
        {
            var order = new Order();
            order.UserName = this.HttpContext.User.Identity.Name;
            order.Total = cartService.GetTotalMoney(cartService.GetCartId(this.HttpContext));
            return View(order);
        }

        /// <summary>
        /// 编辑订单 POST
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public JsonResult _EditOrder(FormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                Order order = new Order();
                TryUpdateModel<Order>(order, formCollection);
                var ispayed = formCollection.Get("isPayed");
                if (ispayed == "IsPayed")
                {
                    order.OrderDate = DateTime.Now;
                    //order.Total=
                    orderService.Create(order);
                    orderService.CreateOrder(order.OrderId, cartService.GetCartId(this.HttpContext));
                    return Json(new { MessageType = 1, MessageContent = "成功生成订单!" });
                }
                return Json(new { MessageType = 0, MessageContent = "请首先支付订单!" });
            }

            return Json(new { MessageType = 0, MessageContent = "订单创建失败" });
        }

    }
}

GGMusicStore/Controllers/StoreController.cs
using Core.MusicInfo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GGMusicStore
{
    public class StoreController : Controller
    {
        private AlbumService albumService;
        private GenreService genreService;
        private ArtistService artistService;

        public StoreController(AlbumService albumService, GenreService genreService, ArtistService artistService)
        {
            this.albumService = albumService;
            this.genreService = genreService;
            this.artistService = artistService;
        }


        /// <summary>
        /// 音乐商店首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Store(string keyword="")
        {
            ViewData["allGenre"] = genreService.GetAll();
            ViewData["keyword"] = keyword;
            return View();
        }

        /// <summary>
        /// 音乐专辑列表
        /// </summary>
        /// <returns></returns>
        public PartialViewResult _ListAlbums(string keyword = "")
        {
            var albums = albumService.GetAll().Where(n => n.AlbumStatus == true);
            if (!string.IsNullOrEmpty(keyword))
            {
                keyword = keyword.ToLower();
                albums = albums.Where(n => (n.Artist.ArtistName.ToLower().Contains(keyword) || n.Genre.GenreName.ToLower().Contains(keyword) || n.AlbumName.ToLower().Contains(keyword)));
            }
            return PartialView(albums);
        }






    }
}

GGMusicStore/Views/Store/Store.cshtml
@{
    ViewBag.Title = "音乐商店";
    var allGenre = (IEnumerable<Genre>)ViewData["allGenre"];
    var keyword = (string)ViewData["keyword"];
}
@Styles.Render("~/Content/Styles/layer")
@Scripts.Render("~/bundles/Scripts/layer")
<!-- banner start -->
<!-- ================ -->
<div id="banner" class="banner" style="height:100px">
    <div class="banner-image"></div>
    <div class="banner-caption" style="top:40%">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 object-non-visible" data-animation-effect="fadeIn">
                    <h1 class="text-center"><span>音乐</span>商店</h1>
                    <div class="input-group col-xs-8 col-xs-offset-2" style="margin-bottom:10px">
                        <input type="text" class="form-control input-searchAlbums" placeholder="可搜索流派、音乐人和专辑名称" style="height:38px">
                        <span class="input-group-btn">
                            <button class="btn btn-primary btn-searchAlbums" type="button">搜索</button>
                        </span>
                    </div>
                    <p class="lead text-center">在这里,您可以浏览和筛选出您想要的音乐,点击唱片查看唱片的详细信息,并将唱片添加到购物车中。 </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- banner end -->

<div class="section" id="storeMain">
    <div class="container">
        <h1 class="text-center title">音乐<span>商店</span></h1>
        <div class="separator"></div>
        <p class="lead text-center">在这里,您可以浏览和筛选出您想要的音乐</p>
        <br>
        <div class="row object-non-visible" data-animation-effect="fadeIn">
            <div class="col-md-12">
                <!-- isotope filters start -->
                <div class="filters text-center">
                    <h4>常用筛选</h4>
                    <ul class="nav nav-pills" data-filter-group="common">
                        <li class="active"><a href="#" data-filter="">全部</a></li>
                        <li><a href="#" data-filter=".new-album">最新专辑</a></li>
                        <li><a href="#" data-filter=".hot-album">畅销专辑</a></li>
                    </ul>
                    <br />
                    <h4>音乐流派</h4>
                    <ul class="nav nav-pills" data-filter-group="genre">
                        <li class="active"><a href="#" data-filter="">全部</a></li>
                        @foreach (var item in allGenre)
                        {
                        <li><a href="#" data-filter=".genre-@item.GenreId">@item.GenreName</a></li>
                        }
                    </ul>
                </div>
                <div id="_ListAlbums">
                    <!-- isotope filters end -->
                    @Html.Action("_ListAlbums", "Store",new RouteValueDictionary { { "keyword",keyword} })
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    $(document).ready(function () {
        $(".banner-image").backstretch('/images/changpiancolor.jpg');
    });

    $('.toCart').click(function () {
        var $this = $(this);
        var toCartNum = $this.prev().val();
        var albumId = $this.data('albumid');
        $.post('@Url.Action("AddToCart","Shopping")', { toCartNum: toCartNum, albumId: albumId, t: (new Date()).valueOf() }, function (data) {
            if (data.MessageType) {
                layer.msg(data.MessageContent, { icon: 1 });
                //异步刷新列表
                $.get('@Url.Action("_ListAlbums", "Store")', { t: (new Date()).valueOf() }, function (html) {
                    $('#_ListAlbums').html(html);
                });
                //异步刷新导航购物车中专辑数量
                $.get('@Url.Action("_CartLayout","Shopping")', function (html) {
                    $('#_CartLayout').html(html);
                })
            }
            else {
                layer.msg(data.MessageContent, { icon: 2 });
            }
        })
    });

    $('.btn-searchAlbums').on('click', function () {
        var keyword = $('.input-searchAlbums').val();
        $.get('@Url.Action("_ListAlbums","Store")', { keyword: keyword, t: (new Date()).valueOf() }, function (html) {
            $('#_ListAlbums').html(html);
            location.href = '#storeMain';
        });
    })

    $('.input-searchAlbums').on('keyup', function (event) {
        if (event.keyCode == 13) {
            $('.btn-searchAlbums').click();
        }
    })



</script>

GGMusicStore/Views/Store/_ListAlbums.cshtml
@model IEnumerable<Album>
<style>
    .isotope-item .btn-default {
        border-radius: 0px;
    }
</style>
@helper IsNewAlbum(Album album = null)
{
    if (album != null)
    {
        if (album.GroundingTime.Subtract(DateTime.Now).Days < 7)
        {
            @:new-album
        }
    }
}
@helper IsHotAlbum(Album album = null)
{
    if ((album.OrderDetails != null && album.OrderDetails.Any()) && album.OrderDetails.Sum(n => n.Quantity) > 10)
    {
        @:hot-album
    }
}
<!-- portfolio items start -->
<div class="isotope-container row grid-space-20">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-3 isotope-item genre-@item.GenreId @IsNewAlbum(item) @IsHotAlbum(item)">
            <div class="image-box">
                <div class="overlay-container">
                    <img src="@item.AlbumArtUrl" alt="">
                    <a class="overlay" data-toggle="modal" data-target="#album-@item.AlbumId">
                        <i class="fa fa-search-plus"></i>
                        <span>@item.Genre.GenreName</span>
                    </a>
                </div>
                <a class="btn btn-default btn-block" data-toggle="modal" data-target="#album-@item.AlbumId" title="@item.AlbumName">
                    @UIHelper.Truncate(item.AlbumName, 25)
                <p class=""><strong>价格:¥@item.DiscountPrice.ToString("0.00")  数量:@item.AlbumNum</strong></p>
            </a>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="album-@item.AlbumId" tabindex="-1" role="dialog" aria-labelledby="album-@item.AlbumId-label" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="album-@item.AlbumId-label">@item.AlbumName @UIHelper.AlbumState(item.AlbumNum, item.AlbumStatus)</h4>
                    </div>
                    <div class="modal-body">
                        <h3>@item.AlbumName</h3>
                        <h6><a href="javaScript:;" class="genreName" data-genredescription="@item.Genre.Description">@item.Genre.GenreName</a> -- <a href="javaScript:;" class="artistName" data-artistdescription="@item.Artist.Description">@item.Artist.ArtistName</a></h6>
                        <div class="row">
                            <div class="col-md-7">
                                @item.Description
                            </div>
                            <div class="col-md-5">
                                <img src="@item.AlbumArtUrl" alt="专辑封面" width="400" height="400">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <label>剩余数量:</label>
                        <label>@item.AlbumNum</label>
                        <label>购买数量:</label>
                        <input class="toCartNum" type="number" value="1" />
                        <button type="button" class="btn btn-sm btn-default toCart" data-dismiss="modal" data-albumid="@item.AlbumId">添加到购物车</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal end -->
    </div>
}
</div>
<!-- portfolio items end -->

<script>


    $('.genreName').on('click', function () {
        layer.tips($(this).data('genredescription'), $(this), { tips: [3, '#55acee'] });
    })

    $('.artistName').on('click', function () {
        layer.tips($(this).data('artistdescription'), $(this), { tips: [3, '#55acee'] });
    })
</script>